# -*- coding: utf-8 -*-
"""test_trendsmcp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-0L9WVX1N8OxnYiXpMwqutc6L1JcucC
"""

import requests
import json
import pandas as pd
import datetime
from google.colab import userdata

secret=userdata.get('trendsmcpapikey')

"""Se define un diccionario de los Sources disponibles para que la generación de datos sea dinámica, y que en tiempo de ejecución cambie en header del request api. esto para agilizar la extracción de los datos por metodo, acorde a la documentación del API. (https://www.trendsmcp.ai/docs#overview)



---


| Type    |  Platform / Feed|
| :-------------- | :----------- |
|Google Trends| Top trending search terms on Google right now|
|Google News Top News|	Top news stories from Google News|
|TikTok Trending Hashtags|	Top trending hashtags on TikTok|
|TikTok Trending Searches|	Top trending search terms on TikTok|
|TikTok Shop Hot Products|	Top hot products on TikTok Shop|
|YouTube Trending|	Top trending videos on YouTube|
|X (Twitter) Trending|	Top trending topics on X|
|Reddit Hot Posts|	Hottest posts on Reddit's front page|
|Reddit World News|	Top posts in r/worldnews|
|Wikipedia Trending|	Most-viewed Wikipedia articles today|
|Amazon Best Sellers Top Rated|	Amazon top-rated best sellers across all categories|
|Amazon Best Sellers by Category|	Amazon best sellers filtered by product category|
|App Store Top Free|	Top free apps on the iOS App Store|
|App Store Top Paid|	Top paid apps on the iOS App Store|
|Google Play|	Top apps on Google Play|
|Top Websites	Most-visited| websites globally by traffic rank|
|Spotify Top Podcasts|	Top podcasts on Spotify|
|Steam Most Played|	Top games by concurrent live players|
|GitHub Trending Repos|	Daily trending repositories across all languages|
|IMDb MOVIEmeter|	Top 100 most-popular movies by user activity|
|Open Library Trending Books|	Daily trending books from Open Library|
"""

# Diccionario de tipos de fuentes (sources) para la API
source_types = {
    "Google Trends": "Google Trends",
    "Google News Top News": "Google News Top News",
    "TikTok Trending Hashtags": "TikTok Trending Hashtags",
    "TikTok Trending Searches": "TikTok Trending Searches",
    "TikTok Shop Hot Products": "TikTok Shop Hot Products",
    "YouTube Trending": "YouTube Trending",
    "X (Twitter) Trending": "X (Twitter) Trending",
    "Reddit Hot Posts": "Reddit Hot Posts",
    "Reddit World News": "Reddit World News",
    "Wikipedia Trending": "Wikipedia Trending",
    "Amazon Best Sellers Top Rated": "Amazon Best Sellers Top Rated",
    "Amazon Best Sellers by Category": "Amazon Best Sellers by Category",
    "App Store Top Free": "App Store Top Free",
    "App Store Top Paid": "App Store Top Paid",
    "Google Play": "Google Play",
    "Top Websites": "Top Websites",
    "Spotify Top Podcasts": "Spotify Top Podcasts",
    "Steam Most Played": "Steam Most Played",
    "GitHub Trending Repos": "GitHub Trending Repos",
    "IMDb MOVIEmeter": "IMDb MOVIEmeter",
    "Open Library Trending Books": "Open Library Trending Books"
}

def fetch_and_process_trends(trend_type_value, secret):
    """
    Fetches trending data for a given type from the API, processes it,
    and returns a pandas DataFrame.
    """
    try:
        res = requests.post(
            "https://api.trendsmcp.ai/api",
            headers={"Authorization": secret},
            json={"mode": "get_top_trends", "type": trend_type_value, "limit": 25 }
        )
        res.raise_for_status() # Raise an exception for HTTP errors (4xx or 5xx)

        if res.status_code == 200:
            data = res.json()

            if 'body' in data and isinstance(data['body'], str):
                parsed_body = json.loads(data['body'])
                dfdata = pd.DataFrame(parsed_body['data'])

                # Conditional column assignment based on trend_type_value
                if trend_type_value == "Amazon Best Sellers by Category":
                    dfdata.columns = ['Top', 'TrendingTopic', 'Category']
                elif trend_type_value == "Top Websites":
                    dfdata.columns = ['Top', 'TrendingTopic', 'TrafficRank']
                else:
                    dfdata.columns = ['Top', 'TrendingTopic'] # Generic column name for combined data

                # Add metadata columns
                dfdata['type'] = parsed_body['type']
                dfdata['limit']= parsed_body['limit']
                dfdata['count']= parsed_body['count']
                dfdata['api_timestamp'] = pd.to_datetime(parsed_body['as_of_ts'])
                dfdata['record_timestamp'] = pd.Timestamp.now(tz='UTC')
                dfdata['data_delay'] = dfdata['record_timestamp'] - dfdata['api_timestamp']
                dfdata['source'] = res.request.url
                dfdata['request'] = res.request.body
                dfdata['response_timeelpased'] = res.elapsed.total_seconds()
                dfdata['request_method'] = res.request.method

                return dfdata
            else:
                print(f"Error: 'body' key not found or not a string in response for {trend_type_value}: {data}")
                return pd.DataFrame() # Return empty DataFrame on parsing error
        else:
            print(f"Error: Recibido código de estado HTTP {res.status_code} for {trend_type_value}")
            return pd.DataFrame() # Return empty DataFrame on HTTP error
    except requests.exceptions.RequestException as e:
        print(f"An error occurred while fetching {trend_type_value}: {e}")
        return pd.DataFrame() # Return empty DataFrame on request exception

"""## Obtener y Consolidar Todos los Datos de Tendencias"""

# MAIN
try:
    all_trends_dfs = []

    for display_name, api_type_value in source_types.items():
        print(f"Fetching trends for: {display_name} (API Type: {api_type_value})")
        try:
            df = fetch_and_process_trends(api_type_value, secret)
            if not df.empty:
                all_trends_dfs.append(df)
            else:
                print(f"No data retrieved for {display_name}")
        except Exception as e:
            print(f"Error fetching trends for {display_name}: {e}")

    # Concatenate all DataFrames into a single one
    if all_trends_dfs:
        final_df = pd.concat(all_trends_dfs, ignore_index=True)
        print("\nCombined DataFrame:")
        display(final_df.head())
        display(final_df.info())

        # Save the combined DataFrame to a single CSV file
        current_time = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"{current_time}_all_trending_data.csv"
        final_df.to_csv(filename, index=False)
        print(f"Archivo consolidado guardado como: {filename}")
    else:
        print("No se pudo recuperar datos de tendencias para ninguna de las fuentes.")
except Exception as e:
    print(f"Error en la extracción de datos de TrendingTopic: {e}")

"""## 3. Análisis Exploratorio de Datos (EDA) sobre Datos de Tendencias Consolidado

Dado que hemos alcanzado el límite de la API, cargaremos el archivo CSV previamente guardado para realizar un análisis exploratorio de datos (EDA) completo. Esto nos permitirá comprender la distribución de los datos, identificar patrones y obtener información valiosa.

### 3.1. Cargar el Archivo CSV Consolidado
"""

# Cargar el archivo CSV consolidado
csv_filename = '20260712_203500_all_trending_data.csv'
try:
    df_consolidated = pd.read_csv(csv_filename)
    print(f"Archivo '{csv_filename}' cargado exitosamente.")
    display(df_consolidated.head())
    display(df_consolidated.info())
    display(df_consolidated.describe())
except FileNotFoundError:
    print(f"Error: El archivo '{csv_filename}' no fue encontrado. Por favor, asegúrate de que el archivo exista en la ruta correcta.")
    df_consolidated = pd.DataFrame() # Crear un DataFrame vacío para evitar errores posteriores

"""### 3.2. Preprocesamiento de Datos para Análisis

Convertiremos las columnas de marca de tiempo (`api_timestamp` y `record_timestamp`) a formato `datetime` y `data_delay` a `Timedelta` para permitir cálculos y visualizaciones adecuadas.
"""

# Convertir las columnas de tiempo a formato datetime y timedelta
if not df_consolidated.empty:
    df_consolidated['api_timestamp'] = pd.to_datetime(df_consolidated['api_timestamp'])
    df_consolidated['record_timestamp'] = pd.to_datetime(df_consolidated['record_timestamp'])
    # Convertir 'data_delay' a timedelta. Puede estar en formato de cadena '0 days 00:00:00.123456'
    df_consolidated['data_delay'] = pd.to_timedelta(df_consolidated['data_delay'])

    # Calcular data_delay en segundos para análisis numérico
    df_consolidated['data_delay_seconds'] = df_consolidated['data_delay'].dt.total_seconds()

    print("Columnas de tiempo convertidas y 'data_delay_seconds' calculado.")
    display(df_consolidated.head())
    display(df_consolidated.info())

"""### 3.3. Análisis de la Distribución de Fuentes (Types)

Visualizaremos qué tipos de fuentes (plataformas) han contribuido con la mayor cantidad de datos.
"""

import matplotlib.pyplot as plt
import seaborn as sns

if not df_consolidated.empty:
    plt.figure(figsize=(12, 6))
    sns.countplot(y='type', data=df_consolidated, order=df_consolidated['type'].value_counts().index, palette='viridis', hue='type', legend=False)
    plt.title('Distribución de Tipos de Fuentes de Tendencias')
    plt.xlabel('Número de Entradas')
    plt.ylabel('Tipo de Fuente')
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("DataFrame vacío, no se puede realizar el análisis de distribución de fuentes.")

"""### 3.4. Análisis de la Frescura de los Datos (`data_delay`)

Exploraremos la distribución del `data_delay` (retraso de los datos) para entender la frescura de la información de las diferentes fuentes. Un `data_delay` más bajo indica datos más recientes.
"""

if not df_consolidated.empty and 'data_delay_seconds' in df_consolidated.columns:
    # Calculate data_delay in minutes for plotting
    df_consolidated['data_delay_minutes'] = df_consolidated['data_delay_seconds'] / 60

    plt.figure(figsize=(12, 6))
    sns.histplot(df_consolidated['data_delay_minutes'], bins=30, kde=True) # Convertir a minutos para mejor legibilidad
    plt.title('Distribución del Retraso de Datos (data_delay) en Minutos')
    plt.xlabel('Retraso de Datos (Minutos)')
    plt.ylabel('Frecuencia')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(14, 7))
    sns.boxplot(x='type', y='data_delay_minutes', data=df_consolidated, palette='coolwarm', hue='type', legend=False)
    plt.title('Retraso de Datos (data_delay) por Tipo de Fuente (Minutos)')
    plt.xlabel('Tipo de Fuente')
    plt.ylabel('Retraso de Datos (Minutos)')
    plt.xticks(rotation=90)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("DataFrame vacío o columna 'data_delay_seconds' no encontrada, no se puede realizar el análisis de retraso de datos.")

"""## 3.9. Análisis Avanzado de Trending Topics (Enfoque Marketing y Publicidad)

Dado el interés en analizar los `TrendingTopic` desde una perspectiva de marketing y publicidad, nos centraremos en identificar patrones, palabras clave y la presencia de temas en diferentes plataformas para entender mejor las oportunidades. Excluiremos el análisis de `data_delay` y profundizaremos en el contenido de los `TrendingTopic`.

### 3.9.1. Frecuencia de Palabras Clave en `TrendingTopic`

Identificaremos las palabras clave más comunes dentro de todos los `TrendingTopic` para descubrir temas subyacentes o recurrentes que podrían ser relevantes para campañas de marketing. Para esto, limpiaremos un poco el texto y contaremos las palabras.
"""

from collections import Counter
import re
import pandas as pd

if not df_consolidated.empty:
    # Unir todos los Trending Topics en un solo string
    all_topics = ' '.join(df_consolidated['TrendingTopic'].astype(str).tolist())

    # Convertir a minúsculas y eliminar caracteres no alfanuméricos
    cleaned_topics = re.sub(r'[^a-zA-ZáéíóúÁÉÍÓÚñÑ\s]', '', all_topics).lower()

    # Tokenizar las palabras y eliminar stopwords comunes en español e inglés
    # Añadir más stopwords si es necesario para un análisis más limpio
    stopwords = set([
        'de', 'la', 'el', 'en', 'y', 'a', 'los', 'las', 'un', 'una', 'unos', 'unas',
        'que', 'es', 'se', 'con', 'para', 'por', 'del', 'al', 'lo', 'más', 'o', 'su',
        'mi', 'tu', 'su', 'este', 'esta', 'estos', 'estas', 'como', 'pero', 'sin',
        'no', 'me', 'te', 'le', 'les', 'nos', 'os', 'les', 'sus', 'entre', 'sobre',
        'desde', 'hasta', 'durante', 'mientras', 'ni', 'o sea', 'tal', 'vez', 'donde',
        'quien', 'porque', 'para', 'que',
        'the', 'a', 'an', 'and', 'or', 'is', 'in', 'on', 'at', 'with', 'for', 'of',
        'to', 'from', 'by', 'but', 'not', 'as', 'it', 'its', 'he', 'she', 'they',
        'we', 'you', 'me', 'us', 'him', 'her', 'them', 'this', 'that', 'these', 'those',
        'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'do', 'does', 'did',
        'will', 'would', 'shall', 'should', 'can', 'could', 'may', 'might', 'must', 'new',
        'top', 'products', 'sellers', 'trending', 'store', 'best', 'shop', 'by', 'hot', 'all', 'app'
    ])

    words = [word for word in cleaned_topics.split() if word not in stopwords and len(word) > 2]

    # Contar la frecuencia de cada palabra
    word_counts = Counter(words)

    # Obtener las 20 palabras clave más comunes
    most_common_words = word_counts.most_common(20)

    print("\n--- 20 Palabras Clave Más Comunes en Trending Topics ---")
    for word, count in most_common_words:
        print(f"{word}: {count}")

    # Visualizar las palabras clave más comunes
    plt.figure(figsize=(12, 8))
    # Create a temporary DataFrame for plotting
    plot_df_words = pd.DataFrame(most_common_words, columns=['Word', 'Count'])
    sns.barplot(x='Count', y='Word', data=plot_df_words, palette='magma', hue='Word', legend=False)
    plt.title('20 Palabras Clave Más Comunes en Trending Topics')
    plt.xlabel('Frecuencia')
    plt.ylabel('Palabra Clave')
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("DataFrame vacío, no se puede realizar el análisis de palabras clave.")

"""### 3.9.2. Unicidad y Superposición de `TrendingTopic` entre Fuentes

Analizaremos qué tan únicos son los trending topics para cada fuente y cuánto se superponen entre sí. Esto puede indicar qué plataformas son mejores para encontrar tendencias nicho vs. tendencias más amplias.
"""

if not df_consolidated.empty:
    unique_topics_by_type = {}
    all_topics_set = set(df_consolidated['TrendingTopic'].astype(str).str.lower().unique())

    print("\n--- Unicidad y Superposición de Trending Topics ---")

    for trend_type in df_consolidated['type'].unique():
        topics_in_type = set(df_consolidated[df_consolidated['type'] == trend_type]['TrendingTopic'].astype(str).str.lower().unique())
        unique_topics_by_type[trend_type] = topics_in_type
        print(f"\n{trend_type}: {len(topics_in_type)} temas únicos.")

    # Calcular superposición entre pares de fuentes (ejemplo para las primeras 5)
    sources_to_compare = list(df_consolidated['type'].unique())[:5]

    if len(sources_to_compare) > 1:
        print("\n--- Superposición entre las principales 5 fuentes ---")
        for i in range(len(sources_to_compare)):
            for j in range(i + 1, len(sources_to_compare)):
                source1 = sources_to_compare[i]
                source2 = sources_to_compare[j]

                set1 = unique_topics_by_type.get(source1, set())
                set2 = unique_topics_by_type.get(source2, set())

                intersection = len(set1.intersection(set2))
                union = len(set1.union(set2))

                if union > 0:
                    jaccard_similarity = intersection / union
                else:
                    jaccard_similarity = 0.0 # No common topics if union is 0

                print(f"Similitud de Jaccard entre '{source1}' y '{source2}': {jaccard_similarity:.2f} (Temas comunes: {intersection})")
    else:
        print("No hay suficientes fuentes para comparar superposición.")

    # Visualización de la superposición (Matriz de Similitud de Jaccard)
    if len(df_consolidated['type'].unique()) > 1:
        jaccard_matrix = pd.DataFrame(0.0, index=df_consolidated['type'].unique(), columns=df_consolidated['type'].unique())

        for type1 in df_consolidated['type'].unique():
            for type2 in df_consolidated['type'].unique():
                if type1 == type2:
                    jaccard_matrix.loc[type1, type2] = 1.0
                else:
                    set1 = unique_topics_by_type.get(type1, set())
                    set2 = unique_topics_by_type.get(type2, set())
                    intersection = len(set1.intersection(set2))
                    union = len(set1.union(set2))
                    if union > 0:
                        jaccard_matrix.loc[type1, type2] = intersection / union
                    else:
                        jaccard_matrix.loc[type1, type2] = 0.0

        plt.figure(figsize=(16, 12))
        sns.heatmap(jaccard_matrix, annot=True, cmap='Blues', fmt=".2f", linewidths=.5, linecolor='black')
        plt.title('Matriz de Similitud de Jaccard entre Tipos de Fuentes de Tendencias')
        plt.show()
    else:
        print("No hay suficientes tipos de fuentes para generar la matriz de similitud.")

else:
    print("DataFrame vacío, no se puede realizar el análisis de unicidad y superposición.")

"""### 3.9.3. Trending Topics Más 'Populares' (Basado en la Columna 'Top') por Fuente

Analizaremos los Trending Topics que consistentemente aparecen en las primeras posiciones (`Top` valores más bajos) en cada fuente, ya que estos son a menudo los más relevantes para la atención de marketing.
"""

if not df_consolidated.empty:
    print("\n--- Trending Topics Más 'Populares' por Tipo de Fuente (Top 5 por Rank) ---")
    for trend_type in df_consolidated['type'].unique():
        print(f"\nTipo: {trend_type}")
        # Ordenar por 'Top' y seleccionar los 5 primeros, asegurándose de que 'Top' es numérico
        df_type = df_consolidated[df_consolidated['type'] == trend_type].copy()
        df_type['Top'] = pd.to_numeric(df_type['Top'], errors='coerce') # Convertir a numérico, forzando errores a NaN
        df_type.dropna(subset=['Top'], inplace=True) # Eliminar filas donde 'Top' es NaN

        top_topics_by_rank = df_type.sort_values(by='Top').head(5)
        if not top_topics_by_rank.empty:
            for index, row in top_topics_by_rank.iterrows():
                print(f"  Top {int(row['Top'])}: {row['TrendingTopic']}")
        else:
            print("  No hay Trending Topics con ranking numérico para este tipo.")
else:
    print("DataFrame vacío, no se puede realizar el análisis de trending topics por popularidad.")

"""### 3.9.4. Análisis de `TrafficRank` y `Category` para Marketing

Revisaremos más a fondo las columnas `TrafficRank` (para `Top Websites`) y `Category` (para `Amazon Best Sellers by Category`) para identificar información valiosa desde una perspectiva de marketing.

### 3.9.5. Análisis de Series de Tiempo del Ranking de Trending Topics por Fuente

Para entender cómo evolucionan las tendencias, visualizaremos el ranking de los Top 25 `TrendingTopic` para cada tipo de fuente a lo largo del tiempo. Aunque el conjunto de datos actual (`df_consolidated`) representa una única instantánea, esta visualización sentará las bases para observar cambios en el ranking si se recopilaran datos en múltiples momentos.
"""

import matplotlib.pyplot as plt
import seaborn as sns

if not df_consolidated.empty:
    unique_types = df_consolidated['type'].unique()

    print("\n--- Análisis de Series de Tiempo del Ranking (Top 25) por Tipo de Fuente ---")

    for trend_type in unique_types:
        print(f"\nGenerando gráfico para: {trend_type}")

        # Filtrar por tipo y tomar los Top 25 (o menos si no hay 25)
        df_type_filtered = df_consolidated[df_consolidated['type'] == trend_type].sort_values(by='Top').head(25).copy()

        if not df_type_filtered.empty:
            # Asegurarse de que 'api_timestamp' es datetime y 'Top' es numérico
            df_type_filtered['api_timestamp'] = pd.to_datetime(df_type_filtered['api_timestamp'])
            df_type_filtered['Top'] = pd.to_numeric(df_type_filtered['Top'], errors='coerce')
            df_type_filtered.dropna(subset=['Top'], inplace=True)

            if not df_type_filtered.empty and len(df_type_filtered['api_timestamp'].unique()) > 1: # Check for actual time variation
                plt.figure(figsize=(18, 10)) # Increased figure size
                sns.lineplot(x='api_timestamp', y='Top', hue='TrendingTopic', data=df_type_filtered, marker='o', palette='tab10')
                plt.title(f'Evolución del Ranking para {trend_type} (Top 25)')
                plt.xlabel('Fecha y Hora de la API')
                plt.ylabel('Ranking (1 = Mejor)')
                plt.gca().invert_yaxis() # Los rankings más bajos son mejores (Top 1 es el mejor)
                plt.xticks(rotation=45, ha='right')
                plt.grid(True, linestyle='--', alpha=0.7)
                plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
                plt.tight_layout()
                plt.show()
            elif not df_type_filtered.empty:
                # Si solo hay un punto de tiempo, mostrar un barplot o scatter para el ranking
                print(f"Nota: Solo se encontró una marca de tiempo única para '{trend_type}'. Mostrando los rankings actuales en un gráfico de barras.")
                plt.figure(figsize=(15, 9)) # Increased figure size
                sns.barplot(x='Top', y='TrendingTopic', data=df_type_filtered.sort_values(by='Top'), palette='viridis', hue='TrendingTopic', legend=False)
                plt.title(f'Ranking de Trending Topics para {trend_type} (Snapshot)')
                plt.xlabel('Ranking')
                plt.ylabel('Trending Topic')
                plt.gca().invert_xaxis() # Invertir el eje X para que los rangos más bajos estén a la derecha
                plt.grid(axis='x', linestyle='--', alpha=0.7)
                plt.tight_layout()
                plt.show()
            else:
                print(f"No hay datos válidos de Trending Topics con ranking numérico para '{trend_type}' después de la limpieza.")
        else:
            print(f"No hay Trending Topics disponibles para '{trend_type}'.")
else:
    print("DataFrame vacío, no se puede realizar el análisis de series de tiempo.")

if not df_consolidated.empty:
    # Para 'Top Websites': Analizar los sitios web de mayor rango (TrafficRank más bajo = más tráfico)
    top_websites_df = df_consolidated[df_consolidated['type'] == 'Top Websites'].copy()
    if not top_websites_df.empty:
        print("\n--- Debugging 'Top Websites' TrafficRank (before conversion) ---")
        display(top_websites_df['TrafficRank'].head(20))
        display(top_websites_df['TrafficRank'].dtype)

        # Attempt conversion to numeric, handling errors by setting non-convertible values to NaN
        top_websites_df['TrafficRank'] = pd.to_numeric(top_websites_df['TrafficRank'], errors='coerce')

        # Drop rows where 'TrafficRank' is NaN after conversion
        top_websites_df.dropna(subset=['TrafficRank'], inplace=True)

        if not top_websites_df.empty:
            print("\n--- Top 10 Websites por 'TrafficRank' (Los más relevantes para publicidad) ---")
            # Sort by TrafficRank (lower rank is better)
            top_ranked_websites = top_websites_df.sort_values(by='TrafficRank').head(10)
            display(top_ranked_websites[['TrendingTopic', 'TrafficRank']])

            plt.figure(figsize=(12, 7))
            sns.barplot(x='TrafficRank', y='TrendingTopic', data=top_ranked_websites, palette='crest', hue='TrendingTopic', legend=False)
            plt.title('Top 10 Websites por Rango de Tráfico (Menor es Mejor)')
            plt.xlabel('Rango de Tráfico')
            plt.ylabel('Sitio Web')
            plt.gca().invert_xaxis() # Invertir el eje X para que los rangos más bajos estén a la derecha
            plt.grid(axis='x', linestyle='--', alpha=0.7)
            plt.tight_layout()
            plt.show()
        else:
            print("No hay datos válidos de 'TrafficRank' para 'Top Websites' después de la limpieza.")
    else:
        print("No se encontraron 'Top Websites' para analizar.")

    # Para 'Amazon Best Sellers by Category': Identificar categorías con mayor actividad
    amazon_sellers_df = df_consolidated[df_consolidated['type'] == 'Amazon Best Sellers by Category'].copy()
    if not amazon_sellers_df.empty and 'Category' in amazon_sellers_df.columns:
        print("\n--- Distribución de Categorías en Amazon Best Sellers (Oportunidades de Nicho) ---")
        category_counts = amazon_sellers_df['Category'].value_counts().head(10)
        print(category_counts)

        plt.figure(figsize=(14, 8))
        sns.barplot(x=category_counts.values, y=category_counts.index, palette='plasma', hue=category_counts.index, legend=False)
        plt.title('Top 10 Categorías de Productos más Frecuentes en Amazon Best Sellers')
        plt.xlabel('Número de Entradas')
        plt.ylabel('Categoría')
        plt.grid(axis='x', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.show()
    else:
        print("No se encontraron datos de 'Amazon Best Sellers by Category' para analizar.")
else:
    print("DataFrame vacío, no se puede realizar el análisis específico de marketing.")

"""### 3.5. Análisis de la Duración de `TrendingTopic`

Analizaremos la longitud de las cadenas de `TrendingTopic` para ver si hay patrones interesantes entre las diferentes fuentes o tipos.
"""

if not df_consolidated.empty:
    df_consolidated['trending_topic_length'] = df_consolidated['TrendingTopic'].astype(str).apply(len)

    plt.figure(figsize=(12, 6))
    sns.histplot(df_consolidated['trending_topic_length'], bins=30, kde=True)
    plt.title('Distribución de la Longitud de los Trending Topics')
    plt.xlabel('Longitud del Trending Topic')
    plt.ylabel('Frecuencia')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(14, 7))
    sns.boxplot(x='type', y='trending_topic_length', data=df_consolidated, palette='mako', hue='type', legend=False)
    plt.title('Longitud del Trending Topic por Tipo de Fuente')
    plt.xlabel('Tipo de Fuente')
    plt.ylabel('Longitud del Trending Topic')
    plt.xticks(rotation=90)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("DataFrame vacío, no se puede realizar el análisis de longitud de trending topics.")

"""### 3.6. Análisis de `response_timeelpased`

Visualizaremos el tiempo de respuesta de la API para cada tipo de fuente para identificar posibles cuellos de botella o fuentes más lentas.
"""

if not df_consolidated.empty and 'response_timeelpased' in df_consolidated.columns:
    plt.figure(figsize=(14, 7))
    sns.boxplot(x='type', y='response_timeelpased', data=df_consolidated, palette='flare', hue='type', legend=False)
    plt.title('Tiempo de Respuesta de la API (response_timeelpased) por Tipo de Fuente')
    plt.xlabel('Tipo de Fuente')
    plt.ylabel('Tiempo de Respuesta (segundos)')
    plt.xticks(rotation=90)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()
else:
    print("DataFrame vacío o columna 'response_timeelpased' no encontrada, no se puede realizar el análisis de tiempo de respuesta.")

"""### 3.7. Top Trending Topics Globales y por Fuente

Identificaremos los 10 `TrendingTopic` más frecuentes a nivel global y luego por cada tipo de fuente para destacar los temas más populares.
"""

import pandas as pd

if not df_consolidated.empty:
    print("\n--- Top 10 Trending Topics Globales ---")
    top_global_trends = df_consolidated['TrendingTopic'].value_counts().head(10)
    print(top_global_trends)

    plt.figure(figsize=(12, 6))
    # Create a temporary DataFrame for plotting
    plot_df_global_trends = top_global_trends.reset_index()
    plot_df_global_trends.columns = ['TrendingTopic', 'Count']
    sns.barplot(x='Count', y='TrendingTopic', data=plot_df_global_trends, palette='crest', hue='TrendingTopic', legend=False)
    plt.title('Top 10 Trending Topics Globales')
    plt.xlabel('Frecuencia')
    plt.ylabel('Trending Topic')
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

    print("\n--- Top 5 Trending Topics por Tipo de Fuente ---")
    for trend_type in df_consolidated['type'].unique():
        print(f"\nTipo: {trend_type}")
        top_trends_by_type = df_consolidated[df_consolidated['type'] == trend_type]['TrendingTopic'].value_counts().head(5)
        if not top_trends_by_type.empty:
            print(top_trends_by_type)
        else:
            print("No hay Trending Topics para este tipo.")

        # Optional: Visualize top trends per type if needed (can be many plots)
        # For brevity, only showing overall plot now.
else:
    print("DataFrame vacío, no se puede realizar el análisis de top trending topics.")

"""### 3.8. Correlación entre `Top` y `TrafficRank` / `Category`

Para las fuentes que tienen columnas adicionales como `TrafficRank` (Top Websites) o `Category` (Amazon Best Sellers by Category), podemos analizar la relación con la columna `Top`.
"""

if not df_consolidated.empty:
    # Para 'Top Websites'
    top_websites_df = df_consolidated[df_consolidated['type'] == 'Top Websites'].copy()
    if not top_websites_df.empty and 'TrafficRank' in top_websites_df.columns:
        # Convert TrafficRank to numeric for scatter plot if it exists
        top_websites_df['TrafficRank'] = pd.to_numeric(top_websites_df['TrafficRank'], errors='coerce')
        top_websites_df.dropna(subset=['TrafficRank'], inplace=True)

        if not top_websites_df.empty:
            print("\n--- Análisis para 'Top Websites' ---")
            plt.figure(figsize=(12, 7))
            sns.scatterplot(x='Top', y='TrafficRank', data=top_websites_df, size='TrafficRank', sizes=(20, 200), palette='cool') # Removed hue for clarity
            plt.title('Relación entre Top y TrafficRank para Top Websites')
            plt.xlabel('Posición (Top)')
            plt.ylabel('Rango de Tráfico')
            plt.grid(True, linestyle='--', alpha=0.7)
            plt.tight_layout()
            plt.show()
        else:
            print("No hay datos válidos de 'TrafficRank' para 'Top Websites' después de la limpieza para el scatter plot.")

    # Para 'Amazon Best Sellers by Category'
    amazon_sellers_df = df_consolidated[df_consolidated['type'] == 'Amazon Best Sellers by Category'].copy()
    if not amazon_sellers_df.empty and 'Category' in amazon_sellers_df.columns:
        print("\n--- Análisis para 'Amazon Best Sellers by Category' ---")
        plt.figure(figsize=(14, 8))
        # Create a temporary DataFrame for plotting count data
        category_counts_plot = amazon_sellers_df['Category'].value_counts().reset_index()
        category_counts_plot.columns = ['Category', 'Count']
        sns.countplot(y='Category', data=amazon_sellers_df, order=amazon_sellers_df['Category'].value_counts().index, palette='plasma', hue='Category', legend=False)
        plt.title('Distribución de Categorías en Amazon Best Sellers')
        plt.xlabel('Número de Entradas')
        plt.ylabel('Categoría')
        plt.grid(axis='x', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.show()
    else:
        print("No se encontraron datos de 'Amazon Best Sellers by Category' para analizar.")
else:
    print("DataFrame vacío, no se puede realizar el análisis de columnas específicas.")